### ISSUE TITLE
Gas efficiency for community

### ISSUE THREAD

**Issue by obadiaa** [flashbots/mev-research#16]
**Summary:**
</br> Data collection and analysis of Ethereum data in order to quantify the negative externalities caused by current techniques used for MEV-extraction as part of the effort to answer Flashbot Research Question 1.

**Research Question:** [Flashbot Research Question 1](https://github.com/flashbots/mev-research/blob/main/FRPs/frq-1.md). 

**Proposed deliverable:**
- Graph of gas wasted over time
- Breakdown various protocols by gas/arb usage
- Gas/arb usage vs. MEV profits
- Upwards pressure on gas price?
- From bot perspective: wasted efficiency for each bot (how often failing / burning gas vs succeeding)
- Gas wasted conditioned on various events? e.g. certain auctions / rebases

**Comment by fiiiu** [comment]
Closing in favor of future FRP-2 on Measuring MEV #40. Take into account this list for that FRP.
