### ISSUE TITLE
Network overhead for community

### ISSUE THREAD

**Issue by obadiaa** [flashbots/mev-research#17]
**Summary:**
</br> Data collection and analysis of Ethereum data in order to quantify the negative externalities caused by current techniques used for MEV-extraction as part of the effort to answer Flashbot Research Question 1.

**Research Question:** [Flashbot Research Question 1](https://github.com/flashbots/mev-research/blob/main/FRPs/frq-1.md). 

**Proposed deliverable:**
- Percent of blockspace wasted over time
- What is the overhead of a single arb / PGA transaction?
- What is the overhead for a miner? What is the overhead for a full node? How do we measure waste?
- What happens to the p2p network / full nodes with much more priority auctions?
- How many (arb) txs broadcast first time in a block?
- How much worse is this in a stateless world? Or other proof-required-for-tx schemes?
- How many deletions? How many messages came in we already saw (duplication)?
- How spammy are various bots compared to other users? How much more duplication?
- Competition: # of bots per opportunity

**Comment by arthurgervais** [comment]
Very good questions. These measurements will also depend on the number of TCP connections the measuring node(s) maintain, I would therefore recommend to include such numbers to normalize the results.

**Comment by fiiiu** [comment]
Closing in favor of future FRP-2 on Measuring MEV #40. Take into account this list for that FRP.
