### ISSUE TITLE
Survey of non-essential on-chain bot logic

### ISSUE THREAD

**Issue by obadiaa** [flashbots/mev-research#18]
**Summary:**
</br>  By understanding how much non-essential bot logic can be brought off-chain without any security tradeoffs, we can design our bundle processing/switching logic with it in mind. Bringing such logic off-chain would alleviate network congestion.

**Research Question:** [Flashbot Research Question 1](https://github.com/flashbots/mev-research/blob/main/FRPs/frq-1.md). 

**Proposed deliverable:**
- Survey of the logic bots are doing on-chain that doesn't have to do with direct execution.

**Comment by fiiiu** [comment]
Same comments as in #19: do we want a separate FRP? Merge with #19? Do we really need this for our profit switcher?
