### ISSUE TITLE
How much non-essential bot logic can be moved off-chain?

### ISSUE THREAD

**Issue by obadiaa** [flashbots/mev-research#19]
**Summary:**
By understanding how much non-essential bot logic can be brought off-chain without any security tradeoffs, we can design our bundle processing/switching logic with it in mind. Bringing such logic off-chain would alleviate network congestion.

Research Question: Flashbot Research Question 1.

**Proposed deliverable:**
- Study of how much of non-essential bot activity can be moved off-chain
- Formalize trade-off between on-chain / off-chain arb computation

**Comment by fiiiu** [comment]
After the FRP-1 partitioning (see #22), this doesn't quite fit FRP-1 (MEV taxonomy), but it touches FRP-2 (Measuring MEV #40) and FRP-5 (Optimizing extraction #43). 

This might warrant an independent FRP; it seems fairly ambitious to try to formalize the on vs. off chain trade-off, do we really need it for our profit switching logic?

**Comment by obadiaa** [comment]
Important topic but closing this in favor of it listed in other places :)
