### ISSUE TITLE
Break up FRP-1 into more specific/manageable FRPs (or tasks)

### ISSUE THREAD

**Issue by sbaks0820** [flashbots/mev-research#22]
FRP-1 at the moment is a very broad proposal that attempts to tackle many questions regarding the auction mechanism design without a clear breakdown of what needs to be done and what theoretical questions need to be answered. This issue proposes a refactoring and breakdown of FRP-1 into approximately 4-5 FRPs that can each be managed by a research fellow or multiple ones managed by a research fellow *team*.

**Comment by fiiiu** [comment]
Closing in favor of #39, #40, #41, #42, #43, #44.
