### ISSUE TITLE
Ordered blinded transactions 

### ISSUE THREAD

**Issue by omershlo** [flashbots/mev-research#34]
In the context of "privacy to minimize MEV" there are two encryption based solutions : 
1) threshold decryption 
2) timelock encryption 

A problem: If the transaction is encrypted in full :  fee payment data is encrypted (Gas related fields are unknown at time of mining) and therefore miners cannot optimise to take the highest paying transactions. 
on the other hand, if the meta data fields are kept as plaintext they leak information.
Ideally, we would like to have the transaction fully encrypted but still allow the miner to order the ciphertexts that go in a block based on gas alone and ensure max gas is not exceeded. 

Lets say that we have such cryptographic black box that does this magic (maybe based on functional encryption): the box lets a miner learn only the order of transactions based on fee without learning the actual fee. 

An immediate problem is that a miner can abuse the black box to learn the exact gas of a transaction tx as follows:  make a dummy block with X-c gas and add the tx to the block. If the gas limit is reached the miner learns that the tx requires > c  gas. A binary search will reveal the exact gas. 

We claim this issue can be bypassed in (1) and (2). In the threshold decryption case, we already assume a quorum, by allowing an extra round/s of coordination, we can use the threshold to manipulate ciphertexts and to limit the number of ordering attempts done by a miner. 
In the time lock encryption case  - we can make running the black box an operation which takes a specific fraction of the time it takes to open the timelock. 

-----

We hope this information is useful and would love to work on it. 
Comments / questions are welcome. 
credit goes to Dev.

**Comment by Pratyush** [comment]
How about the transaction creator attaches a zero knowledge proof that the encrypted fee lies within a certain bucket? This way miners only learn that fees lie within some bounded range, and can use that to order transactions. Of course, the buckets will have to be coarse to prevent too much leakage, but the cryptography is IMO more efficient and better understood

**Comment by omershlo** [comment]
Might be!  my starting point is prior work that suggested very specific transaction encryption schemes (sgx, veedo , MPC etc..). My claim is that the problem is general to all proposed encryption schemes but to make an efficient solution we want to remove that abstraction and use the specifics of each encryption scheme. For zk solution: if we separately encrypt the meta data and prove zkp on this encryption we need to also provide a proof that the ciphertext used for the zkp encrypts the same meta data as in the original ciphertext used to encrypt the tx (imagine the tx ciphertext is time based VeeDo ). Alternatively - we can directly prove on the tx ciphertext (zkp over timelock puzzle?) 
I think that in both cases it is not trivial to say that zkp is more efficient?

**Comment by Pratyush** [comment]
You’re right that it makes sense only for encryption schemes that can be proved correct in zk efficiently. Maybe using Rescue/Poseidon in block cipher mode to encrypt the fee, and using threshold encryption to encrypt the key (I’m assuming threshold enc based on prime order groups)

**Comment by jannikluhn** [comment]
> In the threshold decryption case, we already assume a quorum, by allowing an extra round/s of coordination, we can use the threshold to manipulate ciphertexts and to limit the number of ordering attempts done by a miner.

I think this is problematic from a networking perspective: If a quorum of miners is needed to check if a transaction can be included or not, an attacker could easily spam the network with invalid (or too cheap) transactions. Today, honest nodes refuse to forward invalid transactions, so spam dries out quickly. But with your approach, transactions have to be gossiped through the whole network to the miners first before they can be discarded.

Another problem is that knowing the order or even the exact gas price is not enough, you also need to know that the sender can actually pay for the gas. So you somehow need to put account balances into the equation.

**Comment by omershlo** [comment]
About the threshold assumption: I was simply "riding" on top of it. If what you say is a concern, the threshold should be adjusted to not allow miners to collude or else the whole point of using threshold based decryption is voided from the first place because the colluding miners will be able to decrypt and front-run. 

About your second point: valid argument. if we do full tx encryption I don't see a way to guarantee to the miner that a transaction is profitable under all circumstances (assuming invalid tx will slash the account in favour of the miner).  we might need to solve it per transaction - a zk proof can become handy.

**Comment by jannikluhn** [comment]
The problem I'm trying to point out is not the threshold assumption, but rather that any single node in the network can't check if a transaction is valid or not. Therefore, transactions are gossiped through the whole network before it is discovered that they are invalid, whereas normally they can be filtered out immediately. This is essentially a DOS vector.

**Comment by omershlo** [comment]
ah yes, I agree. for sure a loose end to handle

**Comment by obadiaa** [comment]
closing this for now :D

**Comment by breckyn** [comment]
Hey if any of y’all will be at ETHDENVER, I’m producing a documentary and
would love to interview you guys. Keep me posted and as always great work.

Respectfully;

Breckyn Hager
