### ISSUE TITLE
Create FRP-2: Measuring MEV extraction

### ISSUE THREAD

**Issue by fiiiu** [flashbots/mev-research#40]
FRP-1 is being partitioned into more manageable chunks #22. FRP-2 will tackle measuring MEV extraction. A proposal needs to be written.

Prior notes taken with @sbaks0820:
Measure PGAs, other MEV extraction strategies, define and concretize measurement infrastructure (reliability and assumptions on data)
Use current inspect tools to find PGA's and measure:
- current gas cost of a single arbitrage (average) taking part in PGAs --> expect this to be a long tail distribution --> try to determine the entire distribution of bots being used --> validate long tail from measurement FIRST
- for each extraction opportunity how many bots are showing up? (which ones are easier to find and whether some relationship can be determined based on the profitability of these opportunities)
General: evaluate assumption whether we are seeing lower/upper bounds with MEV inspect or something else entirely --> validate MEV inspect opportunities (there is an issue in MEV inspect of arbitrage found when there isn't any) --> IMPORTANT: evaluate what assumptions an be made from MEV inspect --> perhaps manual validation? (i think we have enough people involved to put them to work) --> bring with Phil and Stephane
in what way is MEV inspect different from frontrun.me? --> cross validation with MEV inspect

**Comment by fiiiu** [comment]
Take into account the suggested lists in #16 on gas efficiency:
- Graph of gas wasted over time
- Breakdown various protocols by gas/arb usage
- Gas/arb usage vs. MEV profits
- Upwards pressure on gas price?
- From bot perspective: wasted efficiency for each bot (how often failing / burning gas vs succeeding)
- Gas wasted conditioned on various events? e.g. certain auctions / rebases

and #17 on network overhead:
- Percent of blockspace wasted over time
- What is the overhead of a single arb / PGA transaction?
- What is the overhead for a miner? What is the overhead for a full node? How do we measure waste?
- What happens to the p2p network / full nodes with much more priority auctions?
- How many (arb) txs broadcast first time in a block?
- How much worse is this in a stateless world? Or other proof-required-for-tx schemes?
- How many deletions? How many messages came in we already saw (duplication)?
- How spammy are various bots compared to other users? How much more duplication?
- Competition: # of bots per opportunity

**Comment by fiiiu** [comment]
Note, crucially, that we are already doing this in the mev-inspect/mev-explore tandem. That effort is already mature, so we might not need an FRP for this at all. @obadiaa thoughts?

**Comment by obadiaa** [comment]
A simple FRP-2 that puts the tasks into the context of Paper 1 to guide the Explore/Inspect team in what the deliverables are here could be helpful. I don't think we need a separate fellow to take over this though
