### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by AugustDev** [flashbots/mev-research#59]
## Problem
Dead link to `Research Roadmap` in [grants.md](https://github.com/flashbots/mev-research/blob/main/grants.md).

It seems [research_roadmap.md](https://github.com/flashbots/mev-research/blob/6fdc2eac25d3b0636feb7707d3436a6a07c8efd8/research_roadmap.md) used to exist in previous commit, but not anymore. It would be interesting to see new roadmap.

**Comment by obadiaa** [comment]
ty! it's been updated :)
