### ISSUE TITLE
[Event] MEV in 2021: A Year In Review

### ISSUE THREAD

**Issue by obadiaa** [flashbots/mev-research#68]
# MEV in 2021: A Year In Review

Date: Thurs 13th January 2022
Time: 3-5pm UTC
Link: [Youtube stream](https://youtu.be/FmHJnA0FzCs)
Recording: https://youtu.be/V_wlCeVWMgk

*In 2021, Maximal Extractable Value (MEV) grew from a niche concept to one regularly talked about. MEV extraction is now a $1b+ industry that has grown beyond the walls of Ethereum.*
*As we enter 2022, Flashbots invites you to a public virtual event to look back at MEV and its extraction in 2021 on Ethereum, Avalanche, Polygon and other chains.*

[Subscribe to the Flashbots calendar](https://calendar.google.com/calendar/u/0/embed?src=c_7lurqn12ecl64li0ms3kse5vok@group.calendar.google.com)

### Section 1: Exploring the Data (1h)

* A brief Survey of MEV on Ethereum, BSC, Avalanche and Polygon in 2021 by Alex Obadia
_A comparative survey of MEV numbers and activity on multiple chains throughout 2021._

* MEV on Ethereum in 2021 by Luke Van Seters 
_On the negative externalities of MEV on Ethereum and the mechanics by which is is extracted, using numbers from the newly released mev-inspect-py._
  * Resources: [mev-inspect-py repo](https://github.com/flashbots/mev-inspect-py), [mev-inspect-py codebase walkthrough](https://youtu.be/Fuw891c4vA8), [mev-inspect-py docs](https://docs.flashbots.net/flashbots-data/mev-inspect-py/overview)

* MEV on Polygon in 2021: A Case-Study of MEV on Low-Fee Chains by Supragya Raj 
_On MEV extraction on Polygon in 2021, including a focus on adversarial and non-adversarial spamming activity and how such activity exists on other low-fee chains._

* Interplay Between Protocol Design and MEV Strategies on Avalanche by Ward Bradt 
_On MEV extraction on Avalanche in 2021, in particular on how changes to the Avalanche protocol affect MEV extraction strategies and vice versa._

### Section 2: Introducing a Framework & Discussion (45m)

* Blockspace market design.. and its consequences by Hasu 
_We've seen different market structures that lead to different outcomes in terms of MEV numbers and negative externalities to the network.  How does one think about how these mechanisms define market structure?_

* Q&A

**Comment by databu** [comment]
The event disappeared from the calendar linked above.

**Comment by obadiaa** [comment]
@databu thank you! not sure what happened, I just added it back :)

**Comment by oussaki** [comment]
The 1b$ is not well calculated we've seen sandwich attacks added as MEV of millions of dollars while in real they just scratched couple of hundreds of dollars.

**Comment by databu** [comment]
> The event disappeared from the calendar linked above.

again…

**Comment by obadiaa** [comment]
@databu sorry about that! I'm not sure why the event disappeared from the calendar again!

**Comment by silaslenihan** [comment]
Is there a recording available of the stream? The current link doesn't work for that

**Comment by alarrieux** [comment]
Is it possible to make the stream public, keep getting video is private

**Comment by erfan377** [comment]
When do you think we can get the recording?

**Comment by obadiaa** [comment]
@erfan377 HD still processing https://youtu.be/V_wlCeVWMgk
