### ISSUE TITLE
Proposing a research topic for whoever is willing to jump on it 

### ISSUE THREAD

**Issue by thsgr** [flashbots/mev-research#74]
## I am opening this issue to give visibility to an idea that someone might want to explore. 

The topic is to use a probabilistic framework to better assess Realized Extractable Value :

## In short
The goal is to find a more accurate measure of <img src="https://render.githubusercontent.com/render/math?math={\color{white}g_{eff}}"> than <img src="https://render.githubusercontent.com/render/math?math={\color{white}g_{tail}}"> is, and therefore a more accurate measure of the REV lower bound. In the spirit of a more theoretical approach, I believe a probabilistic approach is a way of bypassing the ephemeral property of transactions in the mempool, essentially using a posteriori distribution.
Someone could then say: "Here is the block that would have been mined if it had been "untouched", essentially if transactions had been selected by time arrival I suppose, and here is the actual block that was mined. The gas difference between both makes the REV."

## Background and Problem Statement
The recent article of Alejo Salles [1] provides a lower bound for <img src="https://render.githubusercontent.com/render/math?math={\color{white}REV_{M}}"> that primarily depends on <img src="https://render.githubusercontent.com/render/math?math={\color{white}g_{tail}}">. While <img src="https://render.githubusercontent.com/render/math?math={\color{white}REV \geq s_{MEV} \cdot ( g_{MEV} - g_{tail})}"> holds, it is much too imprecise as the <img src="https://render.githubusercontent.com/render/math?math={\color{white}g_{tail}}"> term is not accurate of the real gas fees mempool distribution. Arguably, <img src="https://render.githubusercontent.com/render/math?math={\color{white}\ g_{eff} < g_{tail}}">, implying REV is even greater than current estimates. In the spirit of a more theoretical approach, the goal of this project is to provide a probabilistic approach to better assess <img src="https://render.githubusercontent.com/render/math?math={\color{white}g_{eff}}">, and thus the lower bound. Going further, this would introduce a model that allows to correctly model a block that would not have been reordered. This would drastically improve the accuracy of MEV measures as until now research has not been able to look back to know what a block without permutations in the mempool would have given.

The goal is to find a distribution, noted <img src="https://render.githubusercontent.com/render/math?math={\color{white}q}">, of transactions' order in the mempool such that <img src="https://render.githubusercontent.com/render/math?math={\color{white}\mathbb{E}_q [g_{block}]}"> better accounts for <img src="https://render.githubusercontent.com/render/math?math={\color{white}g_{eff}}"> than <img src="https://render.githubusercontent.com/render/math?math={\color{white}g_{tail}}"> does (on average). There are two different approaches coming to mind, essentially two different ways of viewing the problem. 

1. Ensemble approach: The search for such distribution eventually boils down to finding a realistic permutation of the transactions, that in that order would be a realistic estimate of what a block not reordered would be. The work is thus to equip the permutation group of transactions in the mempool <img src="https://render.githubusercontent.com/render/math?math={\color{white}S(\text{mempool})}"> with the right probabilistic measure. A natural first question is: does <img src="https://render.githubusercontent.com/render/math?math={\color{white}q \sim \mathbb{U}(S(\text{mempool}))}"> work well enough ? 

2. Statistic approach: monitor the mempool to infer the gas distribution it follows, potentially with non-parametric statistics. Therefore it would be possible to draw a sample block, which would arguably be a better estimate of <img src="https://render.githubusercontent.com/render/math?math={\color{white}g_{eff}}"> than <img src="https://render.githubusercontent.com/render/math?math={\color{white}g_{tail}}">.

## References
[1]https://hackmd.io/@flashbots/quantifying-REV#fn4

**Comment by a1nn1997** [comment]
I like your proposal! And want to be part of it

**Comment by BaldwinCepeda** [comment]
is anyone working on this ?

**Comment by adlai** [comment]
My browser does not display any of the mathematics images in the original post. Please consider using [inline expressions](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions#writing-inline-expressions), e.g. $e^{\frac{i \tau}{2}}+1\equiv 0 $

**Comment by sarahalle** [comment]
I am closing this issue since the conversation is no longer active, but please open a topic on https://collective.flashbots.net/c/research/20 if you are still interested!

**Comment by adlai** [comment]
@sarahalle Why did you mark the issue completed?

**Comment by adlai** [comment]
> please see the closing note

To answer my own question... it looks like GitHub simply defaults to marking "Completed"; yet another reason to support alternatives!
