### ISSUE TITLE
Bundle pricing for large bundles

### ISSUE THREAD

**Issue by JVillella** [flashbots/mev-research#76]
Hi folks, we have been working on block-building, and have recently started to add support for sending larger bundles we find along the way to flashbots.

In debugging the auctions we lost, it quickly became clear that the bundle pricing used today is preferring small bundles w/ high miner payouts, instead of the highest overall payout. This is problematic because it leaves significant MEV on the table for miners/validators.

Here's a real life example that happened yesterday afternoon.

* [Tx 1](https://etherscan.io/tx/0x9ebff93ecf0593bf9a57596b112fde30f0cf5f0ec63ec1425633a4f3876ab6cd) traded `USDT --> ETH` and created a ~0.8 ETH MEV opportunity 
* [Tx 2](https://etherscan.io/tx/0x3cd9e0027532404d2e6eb21f932df30d61ac449ab080746b375d0a7335e7de72) also traded `USDT --> ETH` and created a ~0.003 ETH MEV opportunity.

However, if you put Tx 2 in front of Tx 1 and backrun them as one big bundle it's 0.95 ETH MEV opportunity (due to AMM slippage). N.B. this is the order it landed on chain anyways (but not as one bundle) - so the DeFi user isn't getting a worse exchange rate.

Now let's look at the bundle pricing, simplified to: `mevPerGas = minerPayout / totalGasUsed`. And for further simplification, let's say we paid entire 100% as a payout to the miner.

```
0.95 ETH / (150000 + 116331 + 170353) = 2175 GWEI
0.80 ETH / (150000 + 116331)          = 3004 GWEI
```

The 0.80 ETH opportunity w/ its significantly higher `mevPerGas` (but lower total payout) will win the auction ([and they did](https://etherscan.io/tx/0x6781af360fcfa0ca35702f2a762205c8a67db264a88847f7bee6afdec686dc22)). However, the miner is losing out on 0.15 ETH here.

With bundles ranked according to their `mevPerGas`, adding more transactions to a bundle quickly increases the denominator on the pricing formula and pushes them down the ranking.

We've been discussing some other approaches over here that could help maximize miner payout, but I wanted to first check with you folks if this was something of interest to improve, or if you have thoughts yourselves on it.

**Comment by sambacha** [comment]
You are not account for miners also stealing your bundles.

you can try submitting via our gateway, api.securerpc.com/v1

**Comment by JVillella** [comment]
Hi Sam, do you have a different method for bundle pricing? How does this gateway differ?

As I showed with the example, there's no bundle stealing going on here.

**Comment by sambacha** [comment]
> Hi Sam, do you have a different method for bundle pricing? How does this gateway differ?
> 
> As I showed with the example, there's no bundle stealing going on here.

This gateway differs in that it covers all available flashbots compatible rpc gateways with the added heuristics of over a year's worth of bundle submissions both from public data sets and our own. 

If you would like to talk shoot over a calendar invite to sam@manifoldfinance.com - I can share stats etc of the increased hit rate and more context that is not published publicly at this time. 

as for bundle pricing, we do not expose public our pricing API, however, you can examine the transaction pricing API that it is originally based on at: api.txprice.com/v1
