### ISSUE TITLE
FRP preflight: Quantifying the effects of frontrunning and randomness on UX

### ISSUE THREAD

**Issue by awmacpherson** [flashbots/mev-research#80]
I'm in the process of putting together an FRP to evaluate and compare how well different protocol design patterns can protect users from MEV.

I've been advised by @fiiiu to sound out the general idea here and gather feedback from the community on whether it's worth fleshing this out to a formal proposal. What follows is a brief informal outline:

## Summary

Perhaps the most notorious type of MEV extraction activity in terms of its negative effects on users is frontrunning. Frontrunning has become well-known enough that a slew of novel protocols have appeared that make various claims to solve the issue or "protect users from MEV," whether as an additional layer over Ethereum (e.g. Flashbots Protect) or integrated at the smart contract level (e.g. COW protocol).

While it is fairly easy to see that new designs (using, for example, private order books) prevent certain kinds of attacks, as far as I am aware there have been no systematic studies to quantify the effects on users' utilities and hence evaluate and compare different approaches to "MEV-aware" protocol design. What is missing is a mathematical framework to analyse the UX effects of frontrunning, or more generally, of unpredictable execution state.

## Approach

The starting point for this project is the observation that frontrunning is an instance of a more general problem in concurrent computation: shared state may be subject to an unknown set of updates between commitment and execution of a transaction that reads it. That is, from the caller's perspective, shared state effectively constitutes a *random input* to a message call. Frontrunning is simply the case where the random input distribution models the "intentional" behaviour of an external actor — game theoretically, it can be modelled as the "bid" distribution of a Bayes Nash equlibrium of the searcher game.

The random input leads to a *utility distribution* for the execution, that is, a distribution over the utility line of the caller. The shape of this distribution can be influenced by the design of the function according to preferences that may depend on user type and application.

Very briefly, in this work I propose to:

- Formalise the above discussion with precise definitions
- Develop models for utility distributions of functions in common approaches to dapp and privacy layer design and hence obtain formulas for distribution invariants (such as range and variance) that measure the "UX" impact of randomness; in particular, "frontrunnability." 
- Examples will be drawn from the following classes:
  - AMM swaps, e.g. Uniswap v2/3
  - Order book based exchanges (COW, 0x, traditional CEXes)
  - Overcollateralised lending
  - Private mempools, e.g. Flashbots Protect ("fast" and "slow" mode)
  - NFT auction
  - Some non-financial (e.g. networking) applications, if I can think of any.

This project would fall under the **protocol design** research topic. The primary deliverable would be a formal research article targetting publication in a peer-reviewed academic journal or conference. Secondary deliverables are blog posts and conference presentations.

**Comment by emmanuel-awosika** [comment]
I think this is a topic that's worth researching. Evolving dapp design to minimize the impact of MEV on UX is, in my opinion, a more effective (at least, in the short-term) option than trying to solve it at the consensus level (e.g., with transaction encryption, or something similar). 

Also, are you open to having research contributors on this FRP, if it gets approval? I've done some writing on MEV ([here](https://www.alchemy.com/overviews/what-is-mev), [here](https://www.alchemy.com/overviews/mev-boost), [here](https://github.com/ethereum/ethereum-org-website/pull/7333)) and research into MEV-prevention solutions (Flashbots, fair ordering protocols, etc.), so this is something that I'd love to contribute to. Let me know what you think.

ps: [Hashflow](http://hashflow.network/) and [1inch Limit Orders](https://1inch.io/limit-order-protocol/) are other Request-For-Quote (RFQ) DEXes you might want to look at.

**Comment by sambacha** [comment]
Call market design is as least as good as rfq and makes better markets in our testing we did with sushi users for open mev

**Comment by quintuskilbourn** [comment]
This is very awesome and certainly needs to be explored. 

An interesting, related line of thinking is that the "intentional" behaviour approximates some notion of optimality (assuming sufficient competition and sophisticated actors with access to better information like a notion of a true price). The intentional component of the discovery of this optimal execution comes at a cost (gas, external agent profit). How does the utility extraction shape up in comparison to the non-intentional (random?) case. 

I'm thinking about this with something like order flow auctions in mind (see Rook for an example).

**Comment by sarahalle** [comment]
Hi, Andrew. Thanks for outlining these ideas! Since there is interest and engagement, the next step will be to open a PR to formally propose the FRP. I look forward to reading it!

**Comment by awmacpherson** [comment]
> This is very awesome and certainly needs to be explored.
> 
> An interesting, related line of thinking is that the "intentional" behaviour approximates some notion of optimality (assuming sufficient competition and sophisticated actors with access to better information like a notion of a true price). The intentional component of the discovery of this optimal execution comes at a cost (gas, external agent profit). How does the utility extraction shape up in comparison to the non-intentional (random?) case.
> 
> I'm thinking about this with something like order flow auctions in mind (see Rook for an example).
> 
> (I realise the above might be a bit vague, but happy to hop on a call at some point, irrespective of the approval of the FRP)

It sounds very close to things I was thinking about and may include in this project. In particular, the RFQ model is among the list of examples I was hoping to study (e.g. CoW, Rook). Hit me up on TG and let's discuss.

> Hi, Andrew. Thanks for outlining these ideas! Since there is interest and engagement, the next step will be to open a PR to formally propose the FRP. I look forward to reading it!

Thanks! Working on it.

**Comment by awmacpherson** [comment]
PR submitted, hence closing this issue.
